name: my-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  name: mohith

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "hi, hello I am $name"

  second-job:
    runs-on: ubuntu-latest
    env:
      job: jobless
    steps:
      - name: Second step
        run: echo "hi, I am $name and I am $job"
